version: '3.7'
services:
  redis:
    image: redis:6.0
    ports:
      - 6379:6379
  app:
    build: .
    environment:
      - REDIS_HOST=redis:6379
      - PORT=3000
    ports:
      - 3000:3000
    depends_on:
      - redis